### ISSUE TITLE
Disconnected projects segments

### ISSUE THREAD

**Issue by PedroBelavenutti** [forsys-sp/patchmax#32]
appear to happen when project runs out of stands

**Comment by michelledayusfs** [comment]
Actually, this is a true disconnection. Pedro's network has spatial gaps so there is no adjacency. This would probably require preprocessing the dataset to fill in the gaps. Or have patchmax be able to jump to a second graph network to continue the problem?

**Comment by codyevers** [comment]
@PedroBelavenutti this should now be fixed. The issue occurred when forsys would run out of adjacent stands, it would continue to grow into the remaining stands based on their index number (and not distance)
